### ISSUE TITLE
util.rcpath broken

### ISSUE THREAD

**Issue by iblis17** [couchapp/couchapp#169]
``` shell
% COUCHAPPCONF_PATH='/tmp' couchapp help
2015-08-24 00:13:18 [CRITICAL] too many values to unpack

Traceback (most recent call last):
  File "/usr/home/iblis/venv/couchapp/lib/python2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/dispatch.py", line 51, in dispatch
    return _dispatch(args)
  File "/usr/home/iblis/venv/couchapp/lib/python2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/dispatch.py", line 66, in _dispatch
    conf = Config()
  File "/usr/home/iblis/venv/couchapp/lib/python2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/config.py", line 26, in __init__
    self.rc_path = util.rcpath()
  File "/usr/home/iblis/venv/couchapp/lib/python2.7/site-packages/Couchapp-1.0.1-py2.7.egg/couchapp/util.py", line 221, in rcpath
    for f, kind in os.listdir(p):
ValueError: too many values to unpack
```

**Comment by BigBlueHat** [comment]
Closed via merging #171 in 384bcc7c39d0b9cb9850c1453af53925654903e1

Thanks @iblis17 !
