### ISSUE TITLE
[appveyor] run testing and build artifacts

### ISSUE THREAD

**Issue by iblis17** [couchapp/couchapp#186]
Appveyor provides windows ci env.
Let's try it out and leverage the 'artifacts' feature to build the windows binary!

**Comment by iblis17** [comment]
Got some dir access error
```
=====================================================================
ERROR: testClone (tests.test_cli.CliTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\couchapp\tests\test_cli.py", line 39, in setUp
    self.tempdir = _tempdir()
  File "C:\projects\couchapp\tests\test_cli.py", line 30, in _tempdir
    os.unlink(fname)
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\tmpb1djax'
-------------------- >> begin captured logging << --------------------
couchapp.client: DEBUG: Resource uri: http://127.0.0.1:5984/couchapp-test
```

**Comment by iblis17** [comment]
OMG, lots of testing failed because i input unix style path as testing function args.

I decide to skip fixing testing on windows at first, and let standalone binary build ...

**Comment by iblis17** [comment]
Now appveyor will run `tests/test_cli.py`  after the standalone exe built. This will do blackbox testing for basic functions with the exe.

@BigBlueHat 
Would you setup `appveyor` for us? I do not have the webhook permission...
