### ISSUE TITLE
password ending with @

### ISSUE THREAD

**Issue by holymoly** [couchapp/couchapp#233]
I used a randomized password wich ended on @. Is there a way to push the app with authentication on?
Like: couchapp push http://user:asdf@@1.2.3.4:5984/helloworld
Curl has a -u option where I can specify user and password outside the url.

**Comment by iblis17** [comment]
Hi @holymoly 
How about encode `asdf@` as `asdf%40`?
So just push with `http://user:asdf%40@1.2.3.4:5984/helloworld`.
I do not test it yet... please let us known if it works or not :smile_cat:

**Comment by holymoly** [comment]
Nope,

```
 2016-05-04 20:12:16 [CRITICAL] {'msg': '', 'status_int': 401, 'response': <couchapp.client.CouchdbResponse object at 0x109f90d90>}

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/couchapp/dispatch.py", line 45, in dispatch
    return _dispatch(args)
  File "/usr/local/lib/python2.7/site-packages/couchapp/dispatch.py", line 92, in _dispatch
    return fun(conf, conf.app_dir, *args, **opts)
  File "/usr/local/lib/python2.7/site-packages/couchapp/commands.py", line 72, in push
    dbs = conf.get_dbs(dest)
  File "/usr/local/lib/python2.7/site-packages/couchapp/config.py", line 159, in get_dbs
    return [Database(dburl, use_proxy=use_proxy) for dburl in dburls]
  File "/usr/local/lib/python2.7/site-packages/couchapp/client.py", line 227, in __init__
    self.res.head()
  File "/usr/local/lib/python2.7/site-packages/restkit/resource.py", line 122, in head
    params_dict=params_dict, **params)
  File "/usr/local/lib/python2.7/site-packages/couchapp/client.py", line 142, in request
    raise Unauthorized(e)
Unauthorized: {'msg': '', 'status_int': 401, 'response': <couchapp.client.CouchdbResponse object at 0x109f90d90>} 
```

**Comment by iblis17** [comment]
Hmm... This will work currently..
```
└─[iblis@imfsa]% couchapp push -d http://test:foo\@@localhost:5984/test
```

But I think that provide cli option like curl does will be more resonable.

**Comment by holymoly** [comment]
thanks
