### ISSUE TITLE
Couchapp push fails when using couchdb v2.1.1

### ISSUE THREAD

**Issue by Edward-Lombe** [couchapp/couchapp#247]
Sorry wish I had more detail to post here, recently upgraded to v2.1.1, found out that `couchapp push` would hang for a minute or so and then fail with an error as follows. Downgrading to couchdb 2.0.0 fixed this issue. Using the verbose option on the push seemed to indicate that it was unable to push the design document.

```text
Traceback (most recent call last):
  File "/Users/edwardlombe/src/couchapp/couchapp/dispatch.py", line 45, in dispatch
    return _dispatch(args)
  File "/Users/edwardlombe/src/couchapp/couchapp/dispatch.py", line 92, in _dispatch
    return fun(conf, conf.app_dir, *args, **opts)
  File "/Users/edwardlombe/src/couchapp/couchapp/commands.py", line 100, in push
    doc.push(dbs, noatomic, browse, force)
  File "/Users/edwardlombe/src/couchapp/couchapp/localdoc.py", line 125, in push
    db.save_doc(doc, force_update=True)
  File "/Users/edwardlombe/src/couchapp/couchapp/client.py", line 299, in save_doc
    resp = self.res.put(docid, payload=json.dumps(doc), **params)
  File "/usr/local/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/edwardlombe/src/couchapp/couchapp/client.py", line 144, in request
    raise RequestFailed(str(e))
RequestFailed: {"error":"unknown_error","reason":"undefined"}
```

**Comment by iblis17** [comment]
master works for me.
Could you try it out?

**Comment by daveismith** [comment]
I'm getting the same issue:
Couchapp: v1.1.0 (installed with sudo pip install -e git+http://github.com/couchapp/couchapp.git#egg=Couchapp)
CouchDB: 2.1.1 
OS: Mac OS X
Repo trying to install: https://github.com/jchris/sofa

**Comment by daveismith** [comment]
My issue seems to be related to https://github.com/apache/couchdb/issues/979

**Comment by Edward-Lombe** [comment]
It's probably ok to close this issue now, but I would like to add that it seems some better error messages are needed, for example, if you have a validate_doc_update.js that throws an error, pushapps does not give any indication of that, and gives a rather difficult to decipher error message.
