### ISSUE TITLE
I'm using couchapp 0.7.5 and it cannot push with couchdb 2.3.0

### ISSUE THREAD

**Issue by raoyitao** [couchapp/couchapp#251]
I'm using couchapp 0.7.5 and it can push my web app to couchdb 1.6.0, but it cannot work with couchdb 2.3.0 which is hosted in redhat 7. I got an error hard to understand:

Traceback (most recent call last):
  File "/Users/edwardlombe/src/couchapp/couchapp/dispatch.py", line 45, in dispatch
    return _dispatch(args)
  File "/Users/edwardlombe/src/couchapp/couchapp/dispatch.py", line 92, in _dispatch
    return fun(conf, conf.app_dir, *args, **opts)
  File "/Users/edwardlombe/src/couchapp/couchapp/commands.py", line 100, in push
    doc.push(dbs, noatomic, browse, force)
  File "/Users/edwardlombe/src/couchapp/couchapp/localdoc.py", line 125, in push
    db.save_doc(doc, force_update=True)
  File "/Users/edwardlombe/src/couchapp/couchapp/client.py", line 299, in save_doc
    resp = self.res.put(docid, payload=json.dumps(doc), **params)
  File "/usr/local/lib/python2.7/site-packages/restkit/resource.py", line 153, in put
    headers=headers, params_dict=params_dict, **params)
  File "/Users/edwardlombe/src/couchapp/couchapp/client.py", line 144, in request
    raise RequestFailed(str(e))
RequestFailed: {"error":"unknown_error","reason":"undefined"}

Is couchapp 0.7.5 too old or I should update to a new version? Now I 'm not a privileged user to update it, has anyone seen this issue and how to solve it?

**Comment by raoyitao** [comment]
This post can be closed, I found that couchjs could not work properly and there will be a segfault error when creating views through http request. It's a couchDB issue, maybe couchDB should provide clear error message.
